### ISSUE TITLE
Search bar spacing/sizing

### ISSUE THREAD

**Issue by cryptobanjo** [tellor-io/tellorscan#17]
Lets try and get as close to the sizing from my Figma sketch and/or etherscan.  I think generally everything is a bit too large.  Here are some comparisons.

Compared to etherscan:
<img width="976" alt="Screen Shot 2019-05-19 at 11 49 41 AM" src="https://user-images.githubusercontent.com/47423844/58031581-b2ad0780-7aee-11e9-9275-f5188b71852c.png">
Figma mockup:
<img width="629" alt="Screen Shot 2019-05-20 at 11 01 08 AM" src="https://user-images.githubusercontent.com/47423844/58031527-96a96600-7aee-11e9-8f42-d391cc0981de.png">
current:
<img width="964" alt="Screen Shot 2019-05-20 at 11 00 51 AM" src="https://user-images.githubusercontent.com/47423844/58031531-98732980-7aee-11e9-8066-e8b1392d655f.png">

**Comment by mdcoon** [comment]
done
