### ISSUE TITLE
Various text is squishing together.

### ISSUE THREAD

**Issue by cryptobanjo** [tellor-io/tellorscan#18]
Here is what I'm seeing on my MacBook:   
<img width="478" alt="Screen Shot 2019-05-19 at 11 44 51 AM" src="https://user-images.githubusercontent.com/47423844/58031786-2222f700-7aef-11e9-9a5e-2d93ef1c8e0b.png">
<img width="443" alt="Screen Shot 2019-05-19 at 11 51 55 AM" src="https://user-images.githubusercontent.com/47423844/58031799-29e29b80-7aef-11e9-990b-56613c8ad438.png">

Lets optimize the way it squishes and reacts to various browser sizes.

**Comment by mdcoon** [comment]
Changed sizing but display looks ok on my machine. Please let me know if new sizes fix it.
