### ISSUE TITLE
Current request Icon and Tip icon

### ISSUE THREAD

**Issue by cryptobanjo** [tellor-io/tellorscan#19]
The current request icon is out of alignment.  
and the tip icon doesn't match the look of the other icons.  Maybe thinner or lets see if we can find one that feels in the same family as the others.
<img width="408" alt="Screen Shot 2019-05-19 at 11 43 43 AM" src="https://user-images.githubusercontent.com/47423844/58032016-b1c8a580-7aef-11e9-8a4d-59e607b0fda2.png">

**Comment by mdcoon** [comment]
Sizing issue. Fixed.
