### ISSUE TITLE
Scroll bar "pathway" visible when not needed

### ISSUE THREAD

**Issue by cryptobanjo** [tellor-io/tellorscan#22]
On the right side you can see the pathway of the scroll bar when its not needed.  Looks like an error.

<img width="572" alt="Screen Shot 2019-05-20 at 11 15 01 AM" src="https://user-images.githubusercontent.com/47423844/58032429-93af7500-7af0-11e9-9ab9-fde5eb158467.png">

**Comment by mdcoon** [comment]
I tried to set overflow to auto. I can't see whether this made a difference since it doesn't show up on my machine. Please verify and reopen if not fixed.
