### ISSUE TITLE
Inconsistent shadows

### ISSUE THREAD

**Issue by cryptobanjo** [tellor-io/tellorscan#24]
<img width="112" alt="Screen Shot 2019-05-20 at 11 17 18 AM" src="https://user-images.githubusercontent.com/47423844/58032567-dd985b00-7af0-11e9-8b22-8f82cd8b452b.png">
<img width="653" alt="Screen Shot 2019-05-20 at 11 17 14 AM" src="https://user-images.githubusercontent.com/47423844/58032568-dec98800-7af0-11e9-91d7-9cc2f4560c5b.png">

**Comment by mdcoon** [comment]
These should all be cleared up now. Please verify and reopen if I missed something.
