### ISSUE TITLE
recent request tips graph 

### ISSUE THREAD

**Issue by cryptobanjo** [tellor-io/tellorscan#25]
Lots of dead white space here- Lets resize.
<img width="576" alt="Screen Shot 2019-05-20 at 11 30 37 AM" src="https://user-images.githubusercontent.com/47423844/58033704-f6a20b80-7af2-11e9-9309-367bbc924784.png">

**Comment by mdcoon** [comment]
I set a min height on the chart. I tweaked this best I could but the underlying chart lib limits how flexible we can be on the height.
