### ISSUE TITLE
Make faster way to pull everything

### ISSUE THREAD

**Issue by themandalore** [tellor-io/tellorscan#29]
its way way too long...

**Comment by mdcoon** [comment]
Simplified data initialization and removed some calls that were expensive. Namely:
- No longer pulls blocks at init time. Only pulls events.
- No longer pulls mining order for each new value. Waits until dispute time when it matters
- No longer stores each item during init. Stores all items at the outset after pulling all data into memory.
- No longer updates UI for each incoming item. Does one update after all init data pulled.
